webtalk_init -webtalk_dir /net/s/jdomingos/Documents/S4/EN224-Test-et-verification/2_Hardware/Etape_4/PGCD_e/PGCD_e.sim/sim_1/behav/xsim/xsim.dir/PGCD_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 11 16:41:14 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "202409907_1777491908_210660663_640" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c7d0c19f-6d6a-47fc-9105-9d0786dfb5ae" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "862d32b7bb9f4a9c93e5fb86ad5cb9de" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "61" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.8.2003 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3799.499 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "132308_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2388705454 -regid "202409907_1777491908_210660663_640" -xml /net/s/jdomingos/Documents/S4/EN224-Test-et-verification/2_Hardware/Etape_4/PGCD_e/PGCD_e.sim/sim_1/behav/xsim/xsim.dir/PGCD_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /net/s/jdomingos/Documents/S4/EN224-Test-et-verification/2_Hardware/Etape_4/PGCD_e/PGCD_e.sim/sim_1/behav/xsim/xsim.dir/PGCD_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /net/s/jdomingos/Documents/S4/EN224-Test-et-verification/2_Hardware/Etape_4/PGCD_e/PGCD_e.sim/sim_1/behav/xsim/xsim.dir/PGCD_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
